# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 860395a9178bba5c892fcc301e993cb6561403cc454a51e31ff59de73ccaa85c5c94a73b0992658ea0dfe3a7fc42ed24949bf8c16e9c9d11646ece347c686c01

test:
  secret_key_base: 14b431c6bb853b1298bb3b4ee0e05c47e06d419ee0b8dd8f82f5d07694ecece84508beb7e6cdb4263b26ddbfb16a9af4b519b7a8f7463097db96af879626669d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
